services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - "/usr/app/node_modules"
      - "./:/usr/app"
  react-test-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "/usr/app/node_modules"
      - "./:/usr/app"
    command: ["npm", "run", "test"]
